### PR TITLE
Enable authentication and channel binding

### PR DESCRIPTION
**Pull request by laszlohordos**
Allow to get the remot static public key for raw public key authentication and allow to get the handshake hash to securely bind the channel. Add the CreateKeyPair function to generate X448 and X25519 curve keys.

### CODE REVIEW

**Comment by nazar-pc** [comment]
Thanks for this contribution!
I looked at latest version of the specification and I don't see `GetRemotePublicKey()` method there. I've tried not to add methods that are not defined in the spec, so can you clarify why is it needed here?

**Comment by nazar-pc** [comment]
Also please don't build noise-c.js and noise-c.wasm, I'll recompile them myself.

**Comment by laszlohordos** [comment]
One of the most important motivation of Noise protocol compare to TLS is the flexibility of raw key authentication. Unless you want me to point to Noise socket discussion and links where it is explained I just copied from the spec the parts that mention the authentication. 
`The XX pattern is the most generically useful, since it supports mutual authentication and transmission of static public keys.`

Without knowing the public key of other party the protocol can not verify who is talking with. The TLS handshake access to certificate and Noise needs to access to the remote public key. If you have any question I'd be happy to answer and I thank you for this library. This is very helpful for me so I appreciate you work and just let me know how can I improve and help. I don't know why the job is failing now after I fixed the typo. I have unit tests in my node module and testing these new features to allow to generate key pair just like `libsodium-wrappers` but there is no library to generate x448 curve key. The  `GetRemotePublicKey()` is the crucial part of the authentication otherwise the authentication has to be custom made and even though the Noise has made it securely. I have strong crypto/security backend knowledge and I have seen badly implemented solution.   The `GetRemotePublicKey()` and the `GetHandshakeHash` methods are really the fundamentals of authentication and protect against the MitM attack.

**Comment by laszlohordos** [comment]
If you read the (Noise Socket) [https://noisesocket.org/post/1/] and it explains (why)[https://noisesocket.org/post/1/#why] and how to use the remote public key for authentication. 

Your project uses `NK` so you don't care who is the initiator. There are 12 interactive pattern. I use `XK` `XX` `IK` `IX` pattern and they all need the remote key.

I use the noise-c so it obviously have this available. Here are others I used.
(Go)[https://github.com/flynn/noise/blob/master/state.go#L490]
(Haskel)[https://github.com/centromere/cacophony/blob/master/src/Crypto/Noise.hs#L139]

The other language implementation are not very useful so I use the reference noise-c implementation mostly. 

Maybe this (explanation) [https://docs.oracle.com/cd/E19798-01/821-1841/bncbt/index.html] makes you understand why it is so important to have access. If you are still not convinced it is really a key feature and this is the reason behind of all `I?` and `X?` patterns I really need to start from  the basics the explanation. Please read more about the Noise and it's motivation compare to TLS  I'd be happy to explain any of your question. Meanwhile I try to clean up the PR and remove those two files.

**Comment by laszlohordos** [comment]
I added the test but I did not commit the `noise-c.js` and `noise-c.wasm` so the check failed. I had to implement functions in C to avoid some memory leaks. I spent a lot of time on memory issue and I changed the implementation. I'd appreciate very much if you could check my implementation in case there is a memory leak somewhere and you would do the allocation in different way. To me the tests slow down around 1195818th iteration but I don't know how to optimise further. Thank you for this library and I hope this helps others to adopt Noise protocol.

**Comment by nazar-pc** [comment]
Thanks, I'll review this soon.

**Comment by laszlohordos** [comment]
One place where you can optimise the memory allocation when reading/writing messages.

```
ReadMessage: (message, payload_needed = false, fallback_supported = false) ->
	message	= allocate(0, message)
	message_buffer	= allocate_buffer(message, message.length)
	payload_buffer	= null
	if payload_needed
		payload	= allocate(message.length  //constants.NOISE_MAX_PAYLOAD_LEN)
```

The payload is always smaller or equal to `message.length - mac_length` and you don't need to allocate the 64k `constants.NOISE_MAX_PAYLOAD_LEN`.

Also when you are writing message its size won't be longer than:
`(2*54) + (4 * 16) + payload.length`. 

```
WriteMessage: (payload = null) ->
	message	= allocate( (2*54) + (4 * 16) + payload.length  // constants.NOISE_MAX_PAYLOAD_LEN)
```

You save lot's of memory with these modifications.

**Comment by nazar-pc** [comment]
Sorry for the delay, quite busy lately, but I didn't forget about this PR and hope to review, merge and release it soon

**Comment by laszlohordos** [comment]
Thanks, I completed the my project and verified all functions. I can report back that they works as I expected and I found no issue.

**Comment by nazar-pc** [comment]
Thanks a lot for contribution!
I will apply a few tweaks on top and plan to release this as stable version on weekend hopefully.

**Pull request merged**
